# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monster Penguin 
titleShort: MonsterPenguin
email: energy1011@gmail.com

#write html inside the double quotes to display in jumbotron
description: "Blog sobre Inform치tica y Programaci칩n."
#description: "<img src='images/logo-blog.jpg' alt='MonsterPenguin' class='logo'/><h1>Monster Penguin</h1><p>Blog sobre Inform치tica y Programaci칩n.</p>"
baseurl: "/monsterpenguin" # the subpath of your site, e.g. /blog
url: "https://energy1011.github.io" # the base hostname & protocol for your site
github_username:  "Energy1011"
twitter_username: "@Mpenguinblog"

# Build settings
markdown: kramdown
highlighter: rouge
